crop: "cassava"
num_classes: 5
class_names:
  - "Cassava Mosaic Disease"
  - "Cassava Brown Streak Disease"
  - "Cassava Green Mottle"
  - "Cassava Bacterial Blight"
  - "Healthy"
model_type: "tinyvit"
in_channels: 1