crop: "soil"
num_classes: 7
class_names:
  - "Alluvial Soil"
  - "Arid Soil"
  - "Black Soil"
  - "Laterite Soil"
  - "Mountain Soil"
  - "Red Soil"
  - "Yellow Soil"
model_type: "vit_pretrained"
in_channels: 3