crop: "tomato"
num_classes: 10
class_names:
  - "Bacterial Spot"
  - "Early Blight"
  - "Late Blight"
  - "Leaf Mold"
  - "Septoria Leaf Spot"
  - "Spider Mites"
  - "Target Spot"
  - "Yellow Leaf Curl Virus"
  - "Mosaic Virus"
  - "Healthy"
model_type: "vit_pretrained"
in_channels: 3